#pragma once

#include <cstdint>
#include <vector>

namespace mclassic
{

/** Ported from `src/engine/rng.ts`, and required to agree with it exactly.

    mulberry32 is `uint32_t` arithmetic throughout, so "the same music" is a
    claim that can be checked rather than judged: the fixture in
    `src/engine/__goldens__/rng.txt` is generated by the TypeScript and read
    back by the conformance runner.

    The one subtlety in the translation is JavaScript's `+` on the two
    `Math.imul` results. Both operands are int32, so their sum is exact in a
    double, and the surrounding `^` coerces it back with ToInt32 — which is
    modulo 2^32. Unsigned addition is therefore faithful, not merely close.
*/
class Random
{
public:
    explicit Random (uint32_t seed) noexcept : state (seed) {}

    /** The raw draw, before it is scaled into a float. */
    uint32_t nextU32() noexcept
    {
        state += 0x6d2b79f5u;

        const auto a = state;
        auto t = (a ^ (a >> 15)) * (1u | a);
        t = (t + ((t ^ (t >> 7)) * (61u | t))) ^ t;

        return t ^ (t >> 14);
    }

    /** Uniform double in [0, 1). */
    double next() noexcept
    {
        return static_cast<double> (nextU32()) / 4294967296.0;
    }

    /** Uniform integer in [0, n). */
    uint32_t intBelow (uint32_t n) noexcept
    {
        return static_cast<uint32_t> (next() * static_cast<double> (n));
    }

    /** True with probability `p`. */
    bool chance (double p) noexcept
    {
        return next() < p;
    }

    /** Pick an index in [0, n) that is never `avoid`, unless there is no
        alternative. The "no immediate repeats" rule that keeps the randomness
        feeling intentional rather than jittery.
    */
    uint32_t pickIndexAvoiding (uint32_t n, uint32_t avoid)
    {
        if (n <= 1)
            return 0;

        std::vector<uint32_t> candidates;
        candidates.reserve (n);

        for (uint32_t i = 0; i < n; ++i)
            if (i != avoid)
                candidates.push_back (i);

        return candidates[intBelow (static_cast<uint32_t> (candidates.size()))];
    }

private:
    uint32_t state;
};

/** One reflecting step of the walk, as a free function.

    `nextStepIndex` builds a throwaway walk around the *caller's* Rng on every
    brownian step, so the arithmetic has to be reachable without owning one.
*/
double brownianStep (double value, double stepSize, Random& rng) noexcept;

/** A reflecting random walk in [0, 1]; the texture behind M's musical
    randomness.
*/
class BrownianWalk
{
public:
    explicit BrownianWalk (Random r, double startValue = 0.5, double step = 0.15) noexcept
        : rng (r), value (startValue), stepSize (step) {}

    double next() noexcept
    {
        value = brownianStep (value, stepSize, rng);
        return value;
    }

    double current() const noexcept { return value; }

private:
    Random rng;
    double value;
    double stepSize;
};

} // namespace mclassic
