//! Ported from `src/engine/rng.ts`, and required to agree with it exactly.
//!
//! mulberry32 is `u32` arithmetic throughout, so "the same music" is a claim
//! that can be checked rather than judged: the fixture in
//! `src/engine/__goldens__/rng.txt` is generated by the TypeScript and read
//! back by `tests/conformance.rs`.
//!
//! The one subtlety in the translation is JavaScript's `+` on the two
//! `Math.imul` results. Both operands are int32, so their sum is exact in a
//! double, and the surrounding `^` coerces it back with ToInt32 — which is
//! modulo 2^32. `wrapping_add` is therefore faithful, not merely close.

/// Seedable, deterministic uniform source.
#[derive(Clone, Debug)]
pub struct Rng {
    state: u32,
}

impl Rng {
    pub fn new(seed: u32) -> Self {
        Self { state: seed }
    }

    /// The raw draw, before it is scaled into a float.
    pub fn next_u32(&mut self) -> u32 {
        self.state = self.state.wrapping_add(0x6d2b_79f5);
        let a = self.state;

        let mut t = (a ^ (a >> 15)).wrapping_mul(1 | a);
        t = t.wrapping_add((t ^ (t >> 7)).wrapping_mul(61 | t)) ^ t;

        t ^ (t >> 14)
    }

    /// Uniform float in [0, 1).
    pub fn next(&mut self) -> f64 {
        f64::from(self.next_u32()) / 4_294_967_296.0
    }

    /// Uniform integer in [0, n).
    pub fn int(&mut self, n: u32) -> u32 {
        (self.next() * f64::from(n)) as u32
    }

    /// True with probability `p`.
    pub fn chance(&mut self, p: f64) -> bool {
        self.next() < p
    }

    /// Pick an index in [0, n) that is never `avoid`, unless there is no
    /// alternative. The "no immediate repeats" rule that keeps the randomness
    /// feeling intentional rather than jittery.
    pub fn pick_index_avoiding(&mut self, n: u32, avoid: u32) -> u32 {
        if n <= 1 {
            return 0;
        }

        let candidates: Vec<u32> = (0..n).filter(|i| *i != avoid).collect();
        let chosen = self.int(candidates.len() as u32) as usize;

        candidates[chosen]
    }
}

/// A reflecting random walk in [0, 1]; the texture behind M's musical
/// randomness.
#[derive(Clone, Debug)]
pub struct BrownianWalk {
    pub value: f64,
    rng: Rng,
    step_size: f64,
}

impl BrownianWalk {
    pub fn new(rng: Rng) -> Self {
        Self::with_params(rng, 0.5, 0.15)
    }

    pub fn with_params(rng: Rng, value: f64, step_size: f64) -> Self {
        Self { value, rng, step_size }
    }

    pub fn next(&mut self) -> f64 {
        let delta = (self.rng.next() * 2.0 - 1.0) * self.step_size;
        let mut v = self.value + delta;

        if v > 1.0 {
            v = 2.0 - v; // reflect off the top
        }
        if v < 0.0 {
            v = -v; // reflect off the bottom
        }

        v = v.clamp(0.0, 1.0);
        self.value = v;

        v
    }
}
